issue_templates:
  - bug_report.yml
  - feature_request.yml
  - blank_issue.yml
  - planning_epic.yml
  - planning_feature.yml
  - planning_task.yml

contact_links:
  - name: Kubeflow Documentation
    url: https://www.kubeflow.org/
    about: Kubeflow Documentation

  - name: Kubeflow Documentation - Notebooks
    url: https://www.kubeflow.org/docs/components/notebooks/
    about: Kubeflow Notebooks Documentation

  - name: "Kubeflow Slack (join `#kubeflow-notebooks` channel)"
    url: https://www.kubeflow.org/docs/about/community/#kubeflow-slack-channels
    about: Join the Kubeflow Slack