name: GitHub Actions Run Script
run-name: ${{ github.actor }} is (still) testing out GitHub Actions 🚀
on: [push]
jobs:
  example-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Make the script files executable
        run: chmod +x test-script.sh
      - name: Run the scripts
        run: |
          ./test-script.sh
